//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XconApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GC_OQUT
    {
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public string DocStatus { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string Address { get; set; }
        public string NumAtCard { get; set; }
        public string Comments { get; set; }
        public string Project { get; set; }
        public string DocCur { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public string U_MainProject { get; set; }
        public Nullable<int> U_ExpireDay { get; set; }
        public Nullable<System.DateTime> U_EarlyFromDate { get; set; }
        public Nullable<System.DateTime> U_EarlyToDate { get; set; }
        public Nullable<System.DateTime> U_StandardFromDate { get; set; }
        public Nullable<System.DateTime> U_StandardToDate { get; set; }
        public Nullable<System.DateTime> U_OnSiteFromDate { get; set; }
        public Nullable<System.DateTime> U_OnSiteToDate { get; set; }
        public Nullable<decimal> U_EarlyDisc { get; set; }
        public Nullable<decimal> U_StandardDisc { get; set; }
        public Nullable<decimal> U_OnSiteDisc { get; set; }
    }
}
