//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XconApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GC_ORDR
    {
        public int DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string Address { get; set; }
        public string NumAtCard { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public string Doc_Approve { get; set; }
        public Nullable<System.DateTime> Doc_Date { get; set; }
        public Nullable<int> Doc_BaseRef { get; set; }
        public string Doc_Status { get; set; }
        public string Doc_Remark { get; set; }
        public string Doc_AppUser { get; set; }
        public Nullable<System.DateTime> Doc_AppDate { get; set; }
        public string DocCur { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public string ProjectCode { get; set; }
        public string Comment { get; set; }
        public string BoothNo { get; set; }
    }
}
