//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XconApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GC_RDR2
    {
        public int DocNum { get; set; }
        public int LineNum { get; set; }
        public int SubLine { get; set; }
        public string Doc_Size { get; set; }
        public string Doc_Color { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Doc_Label { get; set; }
        public string Doc_Remark1 { get; set; }
        public string Doc_Remark2 { get; set; }
    }
}
