//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XconApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GC_USER
    {
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> UserLevel { get; set; }
    }
}
